version: "3.0"

services:
# Define InfluxDB
  influxdb:
    build: ./influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
 
# Define grafana
  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

# Define Fluentd
  fluentd:
    build: ./fluentd
    ports:
      - "24284:24284"
      - "24284:24284/udp"
      - "5140:5140"
      - "5140:5140/udp"
    depends_on:
      - influxdb
      - grafana